### PR TITLE
Refactor: added a method to register events

### PR DESCRIPTION
**Pull request by esanzgar**
This refactor brings the following advantage:

- no need to run the same checks when adding and removing events
- better ergonomics

Corrected a few things wrong in the tests.

### CODE REVIEW

**Review by robertknight — COMMENTED** [review]
This needs a rebase due to other changes in `BucketBar`. I guess this is where your comments about introducing a utility in the dev sync last week came from? I'd agree that might be useful. Maybe with an API something like:

```js
class ListenerCollection {
  register(target, event, callback);
  // Unregister all listeners. The `destroy` name is more conventional
  // in our code but perhaps `dispose` would be better here.
  destroy(); 
}
```

**Comment by esanzgar** [comment]
Yes, that's what I was thinking...

Would you mind if that's not a class but a function?

**Comment by robertknight** [comment]
> Would you mind if that's not a class but a function?

Sure - if you don't the affordances that a class provides then a function is fine (or better perhaps).

**Comment by esanzgar** [comment]
Replaced by #3099 and #3100

**Pull request closed without merging**
