### PR TITLE
Update dev server document configuration and add some templating

### PR DESCRIPTION
**Pull request by lyzadanger**
This is a merge-ready branch based on https://github.com/hypothesis/client/pull/2418 and with @robertknight 's feedback integrated. 

This PR adds some additional test documents for the local dev web server and organizes some of its setup.

### CODE REVIEW

**Comment by lyzadanger** [comment]
@robertknight Just looking for a sanity check before I merge, as I created a new branch and PR here.

**Comment by robertknight** [comment]
Apologies for the scope creep, but I have a suggestion to simplify the dev server changes in this PR and make the landing page more useful. My suggestion is that we eliminate the preformatted content and the iframes on the landing page and replace it with simple HTML content containing a list of the test documents, enough text for some basic testing and links to useful resources. See the [dev-server-new-homepage](https://github.com/hypothesis/client/tree/dev-server-new-homepage) branch for a sketch. We can add a new test document for testing the iframe support in future, but we're not interested in it most of the time.

In future we could also make it easier to see all the stuff that makes up the dev-server by putting the code and content under the same top-level directory. See the [dev-server-restructure](https://github.com/hypothesis/client/tree/dev-server-restructure) branch for a sketch.

```
dev-server/
  index.js - Code that is currently in `scripts/gulp/dev-server.js`
  create-server.js
  serve-package.js
  templates/ - All the mustache templates that are in `test-documents/` in this PR
```

WDYT?

**Comment by lyzadanger** [comment]
@robertknight The only nit I've noticed with the changes you suggested is that removing the `.html` check from the document pattern means that the dev server will serve `/document/client-config.js/` and `/document/404/` (though you can't really _tell_ the latter because it renders a 404-looking page) because those match the more permissive pattern. Thoughts?

**Comment by robertknight** [comment]
> Thoughts?

You could put the document content in a separate directory from the other templates. With the `dev-server/` restructuring mentioned above it might look something like:

```js
dev-server/
  index.js
  templates/
     client-config.js.mustache
     index.mustache
     documents/
       <content files>
```

There might be an intermediate step that is closer to this PR where `test-documents/` is renamed `dev-server-content/` or something?

Alternatively you could use some other filename pattern (eg. `document-<name>` or `<name>-<document>` for all the content documents).

I don't have super-strong views here, so feel free to go with something else.

**Comment by lyzadanger** [comment]
OK: I've created an additional `documents` directory for clarity. I'm going to land this now! We can tweak as we move forward.

**Comment by lyzadanger** [comment]
For posterity: the incredibly enormous diff is because _Anna Karenina_ is a long novel. Adding a ginormous document is on purpose.

**Pull request merged**
