### PR TITLE
Allow Preact.Fragment shorter syntax

### PR DESCRIPTION
**Pull request by esanzgar**
Currently, the were two ways to return multiple elements at once:

```javascript
   const List = (
        <Fragment>
          <li>A</li>
          <li>B</li>
          <li>C</li>
        </Fragment>
   );
```

or

```javascript
   const List = (
         [
          <li>A</li>
          <li>B</li>
          <li>C</li>
        ]
   );
```

This allows a third, shorter syntax for Fragment:

```javascript
   const List = (
        <>
          <li>A</li>
          <li>B</li>
          <li>C</li>
        </>
   );
```
See also the [Preact documentation about fragments](https://preactjs.com/guide/v10/components#fragments)

### CODE REVIEW

**Comment by robertknight** [comment]
Thanks for the proposal. I'm not sure the benefits outweigh the drawbacks though, given that Fragments are something we've only needed in a moderate number of places (9 files so far). Enabling this means there are two ways to do the same thing so we'd need to choose a convention to use in different contexts and then go and apply it. This isn't hard - but its another thing that new or occasional contributors will need to learn and an extra opportunity for inconsistency between projects.

On a related note, using `Fragment` is slightly different than returning an array because it creates an extra node in the rendered component tree.  A component that returns an array (or nested array) creates a tree like this:

```
List
  |- div
  |- span
```

Whereas using a `Fragment` creates an output tree like this:

```
List
  |- Fragment
       |- div
       |- span
```

This is relevant for the reconciliation/diffing process because React/Preact only look at siblings in the tree to decide whether to update/move an existing component or create/replace one.

**Comment by lyzadanger** [comment]
Thanks for this, Eduardo!

Here's my two cents: I actually _want_ it to stick out like a sore thumb when we use `<Fragment>` because I think, in the majority of cases, it's a marker for components that we should probably refactor. Using `<Fragment>` should, as Rob noted, be a workaround/exception, not a blessed pattern.

Also, I fear that the `<>` syntax would allow this to hide too well: it's hard to grep for and harder to spot in the code.

But please keep PRs like this coming! It's really good to keep improving our processes.

**Comment by esanzgar** [comment]
After a developer chat, we decided to reopen this PR and give it another chance.

**Comment by esanzgar** [comment]
Close in favour of #2956

**Pull request closed without merging**
