### PR TITLE
Set NOTEBOOK_APP_URL env for QA, prod; add to docs

### LINKED ISSUE #2725: Add NOTEBOOK_APP_URL to Jenkinsfile, documentation
For the notebook prototype to be able to launch on QA and prod, it needs the `NOTEBOOK_APP_URL` env set by the `Jenkinsfile`. This might be a good time to add references to this new env to relevant `rst` files in `docs` (search for `SIDEBAR_APP_URL` instances to see where to stick it).

### PR DESCRIPTION
**Pull request by lyzadanger**
This will make Notebook available on QA and prod (though very much still obscured behind a feature flag).

Fixes #2725

### CODE REVIEW

**Review by robertknight — COMMENTED** [review]
It occurred to me that rather than baking this URL into the app though we could instead make it part of the `/api/links` response, as we do with the various URLs that point into activity pages. When selecting the "Open notebook" menu item the URL would need to be passed as part of the message to the client.

The upside is one less piece of configuration. The limitation is that this would always load the version of the notebook served by whichever h server the client is connecting to - you couldn't use it if you wanted to build a custom client. For that purpose we would need some kind of override.

**Comment by robertknight** [comment]
Related to the above comment, I realized the approach used in this PR is useful if we want to make the notebook available in the browser extension and have it load the same version of the client as the sidebar. If we're showing the notebook in an iframe we'll also need to do that to avoid Content Security Policy restrictions on some websites.

**Comment by lyzadanger** [comment]
@robertknight So... :) How would you like to proceed?

**Review by robertknight — APPROVED** [review]
Hi Lyza,

Let's ship this. We may revisit in future if the option to display the notebook inside an iframe, as opposed to a new tab, is removed.

**Pull request merged**
