### PR TITLE
WIP: Debug trouble with UI hook tests

### PR DESCRIPTION
**Pull request by lyzadanger**
I'm using the draft PR feature to get some help (I hope!) on a working branch on which I am having some woes with a particular set of tests.

As part of refactoring how root threads are constructed, I've added a new UI hook: `useRootThread`. For UI components which heretofore used the `rootThread` service, I'm replacing the service with this hook. (This is one step of a larger process).

As part of that, I've updated tests for affected UI components. If I run just the tests for, say, `annotation-viewer-content` or `search-status-bar`, they pass with the updated mocking for a hook (function) versus an injected service.

However, when I run the tests for `sidebar-content`,  all of the tests fail with the same issue:

```
       Chrome Headless 84.0.4147.0 (Mac OS 10.15.5)
      Error: Missing ServiceContext provider to provide "rootThread" prop
          at Object.get (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/util/service-context.js:20:11 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/d1f353252b368a0370ef8010a2ee80ce.browserify.js:352225:11)
          at ImportMap.useService (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/util/service-context.js:114:19 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/d1f353252b368a0370ef8010a2ee80ce.browserify.js:352370:19)
          at ImportMap.useRootThread (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/hooks/use-root-thread.js:9:29 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/d1f353252b368a0370ef8010a2ee80ce.browserify.js:214155:62)
          at y.SearchStatusBar [as constructor] (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/search-status-bar.js:28:18 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/d1f353252b368a0370ef8010a2ee80ce.browserify.js:229712:50)
          at y.H [as render] (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/node_modules/preact/dist/preact.js:1:1 <- 

...and so on
```

It's a bit of a head scratcher to me why anything in `search-status-bar` would be executed during these tests, as that component should be mocked. I'm wondering if there's some nuance to `mockImportedComponents` that I'm not quite understanding.

Any ideas?

The only distinguishing characteristic I can think of here is that `SidebarContent` depends on `SearchStatusBar` and both use the new hook. Something circular somehow?

### CODE REVIEW

**Comment by robertknight** [comment]
Ah - it seems that `SearchStatusBar` is not getting mocked because `mockImportedComponents` doesn't think it is a component. This is happening because `mockImporedtComponents` [checks for a `propTypes` property](https://github.com/hypothesis/client/blob/5f974269837994a858a2efe2ce819d0738eaf8e6/src/test-util/mock-imported-components.js#L7) and `SearchStatusBar` doesn't have one, since it has no props.

**Comment by lyzadanger** [comment]
@robertknight Is there some way for us to document (or even enforce) that all components must have a `propTypes` property? Otherwise someone could run into this again with a component that doesn't take any props...

**Comment by robertknight** [comment]
> @robertknight Is there some way for us to document (or even enforce) that all components must have a propTypes property?

🤔 It could be done with an ESLint plugin or perhaps by getting a Babel plugin to add `propTypes` if missing. I don't know of an existing ESLint/Babel plugin that can be configured to do this off the top of my head.

Another option might be to change the "is a component" check to use different logic that doesn't rely on the existence of `propTypes`. Maybe something that takes into account the name of the function being mocked and the file path (eg. "Anything that starts with a capital letter and is in a directory called 'components'"?)

**Comment by lyzadanger** [comment]
...the module imports `createElement` from `preact`?

**Comment by robertknight** [comment]
> ...the module imports createElement from preact?

That's a good idea, although unfortunately `mockImportedComponents` currently doesn't have access to that information for imports that it processes. It can only look at the file path, symbol name (ie. function/class/variable name) and value of the thing being imported.

**Pull request closed without merging**
