### PR TITLE
[WIP] Target and load/delete annotations for specific frames

### PR DESCRIPTION
**Pull request by RobertHodan**
Loading and deleting annotations only get called for their respective frames

### CODE REVIEW

**Comment by JCCR** [comment]
@sean-roberts 
Thinking of cancelling this because if we merge in https://github.com/hypothesis/client/pull/474 and https://github.com/hypothesis/client/pull/478 a similar result is achieved. The only problem is that this causes a reload of every other search result associated with other frames in the page.
This is not much of a problem in the context of the Readium App, since effectively it would only be the top frame's associated annotation search result set that get reloaded on every frame change. A user normally would not create annotations at the top level in this context so a small to nil set will be reloaded along with the new frame annotation set loading.

**Comment by JCCR** [comment]
The reason why we should look away from this right now is that this relies on identifying frames based on the URI in the `src` attribute.
But depending on how which scenario the frame is set up, I have found that the src uri is not suitable as a unique key. One case is if the frame content is loaded in using a “blob:” URI, that's a guid-like path representing a temporary memory region generated by the browser. Also another case is if the `srcdoc` attribute is used for loading content, the `src` URI would be "about:blank", and the same happens with `document.write`. Finally, what if there's multiple "about:blank" iframes?

**Comment by JCCR** [comment]
The solution to the problem is to generate our own unique key and map that to the iframe instances.
This is what I used in https://github.com/hypothesis/client/pull/478

**Comment by robertknight** [comment]
@JCCR - Should we close this PR for the time being and leave it up to you to re-open a new or revised PR if there are any changes from this that are still relevant?

**Comment by JCCR** [comment]
Yes that works. Thanks

**Comment by robertknight** [comment]
Closing as per https://github.com/hypothesis/client/pull/473#issuecomment-313076116

**Pull request closed without merging**
