### PR TITLE
Fix Mobile Safari Scrolling

### LINKED ISSUE #250: Sidebar cards don't scroll on Safari
_Originally reported as https://github.com/hypothesis/h/issues/3268 by @dwhly._

### Steps to reproduce
1. On iOS (9.3.1) Safari
2. Load via.hypothes.is/example.com
3. Open the sidebar
4. Try to scroll the cards with your finger
### Expected behaviour

The cards should scroll up so that you can see ones further down.
### Actual behaviour

The background page (example.com) scrolls up and down instead, but the cards stay fixed in the sidebar.
### Browser/system information

Current Safari, iOS 9.3.1
### Additional details

Screencast: https://www.youtube.com/watch?v=xEvTE3n9Vcw

### PR DESCRIPTION
**Pull request by sean-roberts**
Fixes #250 

Added the scrolling properties to the app-content-wrapper so that we can get a working scroll behavior for the main thread content. Moving the scroll to that layer caused the geometry to be off again so I updated the virtual thread list to use a scroll root which is the element in the tree that contains the overflow:scroll property. 

I changed the top-bar to position:absolute because the same fixed effect is achieved with absolute positioning and it does not cause as sporadic of jumping behavior to the top bar on mobile scrolling. There is still jumping behavior with the top bar, but that is out of the scope to be solved here. Though adding this absolute positioning made it less bad in the mean time.

### CODE REVIEW

**Comment by dwhly** [comment]
I hope you know how incredibly happy this fix makes me.

**Comment by sean-roberts** [comment]
Talked with Dan and Andrew about the jankiness and some alternatives. We are going to move forward with the janky header and get a ticket up to be prioritized to fix it as we can.

**Comment by robertknight** [comment]
I have tested this in:

Desktop Browsers: Chrome, Firefox, Safari, Edge, IE 11
Mobile Browsers: Mobile Safari, Chrome for Android

All looks good.

**Comment by sean-roberts** [comment]
Merged master in include the tap fixes as well. All LGTM

**Pull request merged**
