### PR TITLE
Adding branding config docs

### PR DESCRIPTION
**Pull request by sean-roberts**
I am not sure how to preview these files but I made pretty basic additions.

### CODE REVIEW

**Comment by robertknight** [comment]
The documentation looks fine in Sphinx, tested using the local doc server. Some quick thoughts:

- Now that I look at the docs, I'm not sure if the term "branding" will be obvious. I think of "branding" as being quite specifically "displaying a logo / WordMark / trademark" on something. Would `style` or `theme` be clearer perhaps? 🤔 
- Related to the above and regardless of whether the name is changed or not, I think it would be useful to include an introduction to the feature, along the lines of "You can customise certain aspects of the look and feel of the sidebar to better fit your site's own look".
- Since this is a brand new feature, we should probably include a note that it may be subject to change in future. See the `services` key for an example of how to do that. My thinking was that once the eLife integration goes live (or perhaps before then) we can commit to making these features stable. That's a subject for a separate discussion which we should have though.

**Comment by seanh** [comment]
Yep, the rst/sphinx syntax looks fine (and `make docs` is not printing out any warnings - it warns about a lot of things)

**Comment by sean-roberts** [comment]
I am opting to leave branding alone for now. We can bring it up if people feel strongly about it. All of those things are synonymous and the predictability of our api naming for this isn't something I would put too much emphasis on - but point taken.

I added the two other items mentioned

**Comment by cllns** [comment]
> Now that I look at the docs, I'm not sure if the term "branding" will be obvious. I think of "branding" as being quite specifically "displaying a logo / WordMark / trademark" on something. Would style or theme be clearer perhaps? 🤔

One data point: I just discovered Hypothesis and was looking to see if it can be themed. I searched "theme" on GitHub and came across this issue to see that it's called "branding". Totally fine for me, just wanted to offer that piece of feedback. :)

**Pull request merged**
