### PR TITLE
Remove `Discovery` class

### PR DESCRIPTION
**Pull request by robertknight**
~~**Depends on https://github.com/hypothesis/client/pull/3611**~~

After https://github.com/hypothesis/client/pull/3611 switches communication to use a new mechanism for establishing a connection between guest and sidebar frames, the previous "discovery" mechanism implemented by `src/shared/discovery.js` is no longer used. This PR this removes it.

### CODE REVIEW

**Comment by esanzgar** [comment]
👍🏼 

What about keeping the class for a few days in case we need to revert back?

**Review by esanzgar — APPROVED** [review]

**Comment by robertknight** [comment]
> What about keeping the class for a few days in case we need to revert back?

We could do. Although all we have to do in that case is just revert this PR. The main reason I can see to delay deleting code is if there is a risk that you make a bunch of other changes in the same area of the code which then has to be patched up if you revert an earlier change.

**Comment by robertknight** [comment]
This is now rebased and ready to land. Per @esanzgar's previous comment, I'm going to let the changes from https://github.com/hypothesis/client/pull/3611 bake in production for a day or so before landing this.

**Comment by robertknight** [comment]
All seems good in production, so I'm going to merge this.

**Pull request merged**
