### PR TITLE
Add ADR for adopting a component-based architecture for the UI

### PR DESCRIPTION
**Pull request by robertknight**
This is a draft ADR which attempts to document at least part of the answer to "how do we use Angular" right now, and some steps we can take to make this more obvious and reduce inconsistencies between different parts of the UI.

The draft is currently written in Markdown because I have yet to learn rST - I'm happy to address that before merging.

### CODE REVIEW

**Comment by seanh** [comment]
> The draft is currently written in Markdown because I have yet to learn rST - I'm happy to address that 
> before merging.

I think it's also fine to to leave this in Markdown if you don't have time (it can always be converted later if it needs to use rST/Sphinx features, although doing so is a _bit_ of a pain)

**Comment by seanh** [comment]
I hope you don't mind but I gave this WIP PR a read.

I think you've got all the information here but it could be clearer it it were distributed more consistently between the different sections of the ADR / if it were more clear what the purpose of each section of the ADR is. Just a little reorganisation of what's already here.

I think maybe the _Context_ section should focus more on the current state of our app and the problems _with the state of our app_ that led to the decision in this ADR. From reading the current ADR, if I understand it correctly, I _think_ it is something like this:

1. Many directives in `src/sidebar/directives` already have a component-like design and can easily be converted to AngularJS `.component()`s. This component-like design is good because [list of benefits of components, as you gave]. But the **problem** with these is that it isn't necessarily obvious, until you know the codebase well, that a component-like architecture is being used here.

2. There are still some `src/sidebar/directives` that do not follow a component-based architecture, and that would not be trivial to turn into `.component()`s. The **problems** with these directives are [lack of encapsulation, lack of clarity about data flow, etc]. (the problems of the pre-component arch are not stated as such in this ADR currently, their inverse is stated as benefits of components.)

3. There is also the top-level of the UI which consists of a mix of router, controller and templates unlike the rest of the UI. What is the **problem** with this? (Presumably it's similar to the problem in 2 above.)

Some of the things that you've mentioned under _Consequences_ as benefits of the decision, seem like they could also be stated under _Context_ as problems with the current situation as well (it's a _great_ list: lack of consistency in how UI components are defined and communicate; hard to understand and refactor parts in isolation; hard for newcomers to understand how it's structured; too many concepts to grok; lack of alignment with how an app would be structured in other frameworks, too tied to AngularJS 1.x, etc).

Historical information about how JavaScript frameworks have evolved over time is interesting to have, and I think it can go in _Context_, but it can also confuse the problem(s) and solution that this ADR is about. so I would put it at the bottom of the _Context_ section not at the top, and I would even put it under a `### Background` heading. 

Also in the _Decision_ section I would say that `.component()` should be used (this is currently not said under _Decision_, only under _Context_, but it is part of the decision not part of the context).

**Comment by robertknight** [comment]
Thanks for this @seanh . Your summary of the problems of the current status is exactly right. I will update the document to reflect that.

**Comment by seanh** [comment]
Just getting a cuppa then taking another look at this

**Comment by seanh** [comment]
Great, awesome to have the first one of these

**Pull request merged**
