### PR TITLE
Upload JS bundles to Sentry and set correct URL prefix

### PR DESCRIPTION
**Pull request by robertknight**
Fix several issues with the Sentry file uploads which prevented Sentry from using the uploaded files.

 - Upload the JS bundles to Sentry as well as the sourcemaps. Sentry reads the `sourceMappingURL` comment from the JS
 - Set the correct URL prefix for the files, so that Sentry knows that, for example, "sidebar.bundle.js" is served at https://cdn.hypothes.is/hypothesis/$VERSION/build/scripts/sidebar.bundle.js

   For Sentry to use a file uploaded in a release, the artifact name (URL prefix + name) must match the URL from which it is served (and referenced in crash reports). The origin of the URL can optionally be shortened to `~`, but we haven't done that here.
 - Finalize the release after uploading files

This is related to https://github.com/hypothesis/client/issues/3681, although the actual fix for that problem is https://github.com/hypothesis/client/pull/4041.

### CODE REVIEW

**Comment by robertknight** [comment]
Example of a Sentry release with correct artifact URLs: https://sentry.io/settings/hypothesis/projects/client/source-maps/1.0.0-sentry-test

Sentry release artifacts

And the output from the build log:

```
$ /data/jenkins/workspace/ient_fix-sentry-sourcemap-upload/node_modules/.bin/sentry-cli releases --org hypothesis --project client files 1.0.0-sentry-test upload-sourcemaps --url-prefix https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/ build/scripts/
> Found 6 release files
> Analyzing 6 sources
> Rewriting sources
> Adding source map references
> Bundled 6 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: hypothesis
> Project: client
> Release: 1.0.0-sentry-test
> Dist: None

Source Map Upload Report
  Minified Scripts
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/annotator.bundle.js (sourcemap at annotator.bundle.js.map)
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/sidebar.bundle.js (sourcemap at sidebar.bundle.js.map)
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/ui-playground.bundle.js (sourcemap at ui-playground.bundle.js.map)
  Source Maps
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/annotator.bundle.js.map
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/sidebar.bundle.js.map
    https://cdn.hypothes.is/hypothesis/1.0.0-sentry-test/build/scripts/ui-playground.bundle.js.map
Done in 1.85s.
```

**Comment by lyzadanger** [comment]
@robertknight 

> Finalize the release after uploading files

Can you expand a little on what this does?

**Review by lyzadanger — APPROVED** [review]
This sounds sensible; I was curious as to what `finalize` does, exactly.

**Comment by robertknight** [comment]
> This sounds sensible; I was curious as to what finalize does, exactly.

It has a few minor effects, explained at https://docs.sentry.io/product/cli/releases/#finalizing-releases:

 > By default a release is created “unreleased”. Finalizing a release means that we fill in a second timestamp on the release record, which is prioritized over date_created when sorting releases in the UI. This also affects what counts as "the next release" for resolving issues, what release is used as the base for associating commits if you use --auto, and creates an entry in the Activity stream.

**Pull request merged**
