### PR TITLE
Add Tailwind support

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR demonstrates the use of updated `frontend-shared` and `frontend-build` packages to add Tailwind support to the client.

Depends on https://github.com/hypothesis/frontend-build/pull/8 (frontend-build support) and package release
Depends on https://github.com/hypothesis/frontend-shared/pull/242 (frontend-shared support) and package release

The three commits here:

1. Adds the Tailwind dependency to the project. Pretty duh.
2. Configures tailwind. Extends the `frontend-shared`-provided Tailwind preset in its config and passes that config on to the CSS-build gulp task (provided by `frontend-build`).
3. Provides an example of restyling a component with Tailwind utility styles.

## Test it out

1. Get `frontend-build` ready: 
    1. [check out this PR branch](https://github.com/hypothesis/frontend-build/pull/8)
    2. In `frontend-build` project directory, run `yalc publish`
2. Get `frontend-shared` ready:
    1. [check out this PR branch](https://github.com/hypothesis/frontend-shared/pull/242)
    2. In `frontend-shared` directory, run `yarn build; yalc publish`
3. Get the `client` ready:
    1. Check out this branch
    2. In the `client` directory, run
    ```
    $ yalc add @hypothesis/frontend-build
    $ yalc add @hypothesis/frontend-shared
    ```

Nowwwww, run `make dev` in the client.

If everything goes right, it should build without crashing. That's step one. Then pop open your browser, visit http://localhost:3000/ and click on the "Help" (?) icon in the top bar. Then click "About this version ->". You should see something akin to:

image

The above includes a component that was restyled here using Tailwind's utility styles.

## Notes

* This PR's tailwind configuration for the client puts it into ["jit" mode](https://tailwindcss.com/docs/just-in-time-mode). You will see some notices to this effect in the console.
* You can take a look at the generated stylesheet (in `build/`) if you're curious to see the output—only Tailwind utility classes we're using will be present.

### CODE REVIEW

**Comment by robertknight** [comment]
I got this error after removing the build directory and running `make dev` on this branch:

```
[12:02:07] Alternate web server started at http://localhost:3002/

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
[12:02:10] 'build-css' errored after 2.04 s
[12:02:10] Error: ENOENT: no such file or directory, stat 'build/styles/sidebar.css'
    at Object.statSync (node:fs:1536:3)
    at trackModified (/Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:422:35)
    at getContext (/Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:609:38)
    at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupTrackingContext.js:177:57
    at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:54:7
    at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/index.js:25:56
    at LazyResult.runOnRoot (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:391:26)
    at LazyResult.async (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:206:17)
[12:02:10] 'watch-css' errored after 2.07 s
[12:02:10] 'watch' errored after 2.07 s
```

I was able to work around this by creating an empty `build/styles/sidebar.css` file using `touch build/styles/sidebar.css` and then re-running `make dev`.

**Comment by robertknight** [comment]
The use of JIT mode means that the generated CSS now depends on the JS sources. Currently if you change JS code to use a "new" Tailwind class that is not used by any existing JS, the CSS output will not include the class. The absolute dumbest way to fix this would be to rebuild CSS whenever any component JS files change:

```diff
diff --git a/gulpfile.mjs b/gulpfile.mjs
index e92e81b56..c5af04bd0 100644
--- a/gulpfile.mjs
+++ b/gulpfile.mjs
@@ -37,7 +37,11 @@ gulp.task(
   'watch-css',
   gulp.series('build-css', function watchCSS() {
     gulp.watch(
-      ['node_modules/katex/dist/katex.min.css', 'src/styles/**/*.scss'],
+      [
+        'node_modules/katex/dist/katex.min.css',
+        'src/styles/**/*.scss',
+        'src/**/components/**/*.js',
+      ],
       gulp.task('build-css')
     );
   })
```

This is a workable solution for the current scale of our projects. Rebuilding CSS from scratch each time will get slower as the project grows however. If SASS / PostCSS / Tailwind have incremental build modes that will be better.

**Comment by lyzadanger** [comment]
> The use of JIT mode means that the generated CSS now depends on the JS sources. Currently if you change JS code to use a "new" Tailwind class that is not used by any existing JS, the CSS output will not include the class. The absolute dumbest way to fix this would be to rebuild CSS whenever any component JS files change:
> 
> ```diff
> diff --git a/gulpfile.mjs b/gulpfile.mjs
> index e92e81b56..c5af04bd0 100644
> --- a/gulpfile.mjs
> +++ b/gulpfile.mjs
> @@ -37,7 +37,11 @@ gulp.task(
>    'watch-css',
>    gulp.series('build-css', function watchCSS() {
>      gulp.watch(
> -      ['node_modules/katex/dist/katex.min.css', 'src/styles/**/*.scss'],
> +      [
> +        'node_modules/katex/dist/katex.min.css',
> +        'src/styles/**/*.scss',
> +        'src/**/components/**/*.js',
> +      ],
>        gulp.task('build-css')
>      );
>    })
> ```
> 
> This is a workable solution for the current scale of our projects. Rebuilding CSS from scratch each time will get slower as the project grows however. If SASS / PostCSS / Tailwind have incremental build modes that will be better.

Tailwind build in JIT mode is super duper fast, so I think the weakest link in the CSS build task here is SASS. I still have a vision of eliminating SASS in the mid-term...

**Comment by lyzadanger** [comment]
> I got this error after removing the build directory and running `make dev` on this branch:
> 
> ```
> [12:02:07] Alternate web server started at http://localhost:3002/
> 
> warn - You have enabled the JIT engine which is currently in preview.
> warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
> [12:02:10] 'build-css' errored after 2.04 s
> [12:02:10] Error: ENOENT: no such file or directory, stat 'build/styles/sidebar.css'
>     at Object.statSync (node:fs:1536:3)
>     at trackModified (/Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:422:35)
>     at getContext (/Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:609:38)
>     at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/lib/setupTrackingContext.js:177:57
>     at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:54:7
>     at /Users/robert/hypothesis/client/node_modules/tailwindcss/lib/jit/index.js:25:56
>     at LazyResult.runOnRoot (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:339:16)
>     at LazyResult.runAsync (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:391:26)
>     at LazyResult.async (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:221:30)
>     at LazyResult.then (/Users/robert/hypothesis/client/node_modules/postcss/lib/lazy-result.js:206:17)
> [12:02:10] 'watch-css' errored after 2.07 s
> [12:02:10] 'watch' errored after 2.07 s
> ```
> 
> I was able to work around this by creating an empty `build/styles/sidebar.css` file using `touch build/styles/sidebar.css` and then re-running `make dev`.

Wow! _Great_ catch. I didn't fully blow away my `build` directory at any point so didn't see this pop up. I'll take a peek.

**Pull request closed without merging**
