### PR TITLE
Upgrade to Yarn v3

### PR DESCRIPTION
**Pull request by robertknight**
Follow the steps at https://yarnpkg.com/getting-started/migration to upgrade to Yarn v3:

 1. `yarn set version berry`
 2. Edit `.yarnrc.yml` to add `nodeLinker: node-modules`.
 3. Run `yarn install` to migrate lockfile
 4. Update `.gitignore` (see comment)
 5. Commit all new/changed files

The initial motivation for this was to fix [warnings about strip-ansi-cjs, string-width-cjs and wrap-ansi-cjs](https://github.com/hypothesis/client/pull/5540) that recently appeared during fresh installs. More generally this gets us onto an actively maintained version of Yarn.

### CODE REVIEW

**Comment by acelaya** [comment]
According to [the documentation](https://yarnpkg.com/getting-started/migration#step-by-step), it says `Run yarn set version berry to enable v2`. But don't we want to update to v3? 🤔

**Review by acelaya — APPROVED** [review]
I have tested the main development commands (`lint`, `test`, `format`, `checkformatting`), and they all work.

The changes don't seem so disruptive (other than the one-time lockfile update), so I would say we give this a try!

One thing to check is if dependabot can handle updates without any further changes.

**Comment by robertknight** [comment]
> One thing to check is if dependabot can handle updates without any further changes.

Good point. Yarn v3 is listed as supported at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems.

**Comment by acelaya** [comment]
> Yarn v3 is listed as supported at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems.

I haven't seen any reference to the yarn version in dependabot's config, so I would expect it to work transparently, but something to check next Monday

**Pull request merged**
