### PR TITLE
Multi-doc: decouple guest from host

### PR DESCRIPTION
**Pull request by JCCR**
This is a part of the NYU project that aims to integrate Readium and Hypothesis.
With the goal of supporting multiple concurrent documents.

This is part one of a series of pull requests that will be based on the initial PR here:
https://github.com/hypothesis/client/pull/344

### Details specific to this PR

This pull request splits some of the coupling between Guest and Sidebar/Host. This is the foundation for the next set of changes. 

- Guest now holds its own reference to the document, and this can differ from the document reference that the Host uses to attach the Sidebar. 
- Guest now creates a separate instance of Annotator bound to its document reference.
- To keep the original functionality intact, for the scenario where there is only one document to bind to, the concept of the "default" guest is introduced. This is the Guest instance that the Sidebar instantiates and both share the same reference to the single document.

### CODE REVIEW

**Comment by robertknight** [comment]
I've got some questions about the multi-document support. I'm sure you have explained much of this to @sean-roberts already.

> With the goal of supporting multiple concurrent documents.

* In Readium are there multiple frames presenting annotatable content at once or just one frame, but one that is not the top-level frame that hosts the sidebar?
* If there are multiple frames, what is in each of them?
* If you create a page note, which document will that annotation be associated with?
* The sidebar currently assumes that it is communicating with a single frame in the host page. How does it know which frame to associate an annotation with after performing search request(s) to the API?

**Comment by JCCR** [comment]
@robertknight 
Hi Robert,

I will try to answer your questions.

> In Readium are there multiple frames presenting annotatable content at once or just one frame, but one that is not the top-level frame that hosts the sidebar?
Depending on how Readium is displaying content it can be one frame (not the top-level), or more than one frame if the page layout dictates there being two pages shown side by side, or using iframes stacked on top of each other in a vertical scrollable area.

Here's an example where there's two iframes shown side by side.
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0202&goto=%7B%22idref%22%3A%22xhtml-003%22%2C%22elementCfi%22%3A%22%2F4%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D&

Here's an example for the scrolling case, showing 2, 3 or more iframes, depending on your vertical screen space:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0112&goto=%7B%22idref%22%3A%22front%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D&

> If there are multiple frames, what is in each of them?
Each iframe is used to host a spine item's (page/chapter) content document, which is typically an XHTML file but can be other formats such as SVG

> If you create a page note, which document will that annotation be associated with?
I'm not certain but if the Readium reader is the main interactive area of the top-level frame we could ask Readium to create a bookmark and use the bookmark's CFI location as the basis for the page note. Readium would figure out which spine item to target and which iframe and document best reflects the current "page".

> The sidebar currently assumes that it is communicating with a single frame in the host page. How does it know which frame to associate an annotation with after performing search request(s) to the API?
I will answer that in a separate comment.

**Comment by sean-roberts** [comment]
If you have any more questions about the iframing and spine items with readium I should be able to answer those directly Rob.

**Comment by sean-roberts** [comment]
Closing open PR. Code is still reachable on evidentpoint:Thesis-PR1-Decouple-Guest-From-Host branch if needed

**Pull request closed without merging**
