### PR TITLE
Add oauth refresh support

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by seanh** [comment]
I still need to test that this actually works in a browser, but I think it can be reviewed already.

@robertknight You might be a good person to review this?

There's currently no error handling if the refresh token response fails. Since this response is done on a `window.setTimeout()` I'm not sure that it's a good time to show an error to the user either. It should probably log an error.

There needs to be better end-to-end error handling if a grant token or refresh token response fails and the client ends up with either no access token, or with an invalid access token. I haven't tried to see what happens currently. Calling `tokenGetter()` should probably raise, and then some higher up code should turn that into some sort of "Try reloading the page" error to the user. In the case of an invalid (expired) access token, rather than an undefined one, `tokenGetter()` should probably just return the access token and then the code that tries to use the access token in an API request (and gets back an error from the API) should turn that into a user error message. I think this can all be done in follow-up PRs?

**Comment by sean-roberts** [comment]
Given this a quick look over, I don't see anything that jumps out at me as a major issue. I'd need to do some testing on it as well.

**Comment by seanh** [comment]
Testing this using [Rob's example site](https://github.com/hypothesis/publisher-account-example-site) and having changed the access token expiry time from one hour to ten seconds server-side, the client seems to  be sending _two_ refresh token requests every ten seconds, with two _different_ refresh tokens. Weird. I'll try to figure out what's going on after lunch.

**Comment by seanh** [comment]
Ok, I think see what the problem is. This is my theory after a little debugging. This problem exists on master as well:

1. `tokenGetter()` is called and kicks off a grant token request to get an access token and store it in `cachedToken`

2. Before the HTTP response comes back `tokenGetter()` is called again, kicks off a second grant token request. You will see two token endpoint requests on master. Whichever HTTP request comes back last presumably overwrites the access token from the first request. It doesn't do any harm, just sends two requests unnecessarily.

On this branch the problem is compounded because:

1. The first grant token request sets a `window.setTimeout()` to do a refresh token request
2. The second grant token request sets a `window.setTimeout()` to do a refresh token request
3. The first timeout ends, the first refresh token is sent (and on receiving the response to this another timeout is set)
4. The second timeout ends, the second refresh token is sent (and on receiving the response to this another timeout is set)
5. It repeats - every time two timeouts are set and two refresh tokens sent

Again, it doesn't really do any harm, it's just always sending two requests instead of one.

**Comment by seanh** [comment]
Closing this as it ended up getting replaced with a series of pull requests, the last of which was https://github.com/hypothesis/client/pull/221

**Pull request closed without merging**
