### PR TITLE
Replace help icon with lighter variant

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR also makes icons with the `top-bar__btn` class have a height of `100%`, maximizing their target areas and helping with alignment.

New look in sidebar:

image

Single annotation view:

image

Note also the hopefully temporary top padding that has been added to the `top-bar__btn` rules:

```
  padding: 1px 3px 0 3px;
```
(adds `1px` top padding). Without this rule, the alignment isn't quite as precise/accurate:

image

### CODE REVIEW

**Comment by robertknight** [comment]
This looks fine in Chrome and Firefox. In Safari 12.1 I noticed that the icon gets clipped slightly at the top:

Screenshot 2019-06-12 17 05 20

**Comment by robertknight** [comment]
Adding one pixel of vertical padding to the `top-bar__btn` container resolves the issue in Safari.  It looks like the `<button>` is clipping its contents in Safari but not Chrome or Firefox perhaps.

**Comment by lyzadanger** [comment]
Thanks for spotting that! Deep breaths. If I set an explicit height on the element to `15px`, it fixes the clipping but the overall alignment still looks, ah, less than perfect to me, what do you think?

image

**Comment by lyzadanger** [comment]
@robertknight OK, try that? I still feel like it's not perfect but it looks tolerable in Chrome and Safari locally. I'm going to step away from this for a while if it still needs more tweaks because I'm losing my mind a bit!

**Comment by robertknight** [comment]
I've confirmed that the `<button class="top-bar__btn">` is clipping its contents ... which offers another option which I think is better:

1. Keep the negative margin from your first commit
2. Set `height: 100%` on `top-bar__btn`. This makes the share and help buttons vertically fill the container but the contents remains centered, providing a bigger hit target.

**Comment by robertknight** [comment]
I haven't figured out _why_ the button gets clipped in Safari but not Firefox/Chrome. Perhaps there is some user agent style that is doing this.

**Pull request merged**
