### PR TITLE
Group `Annotation*` components

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR demonstrates a pattern we could use to group components in the client as the number of components grows. This set of changes groups all `Annotation*` sub-components under an `Annotation` directory and exports `Annotation` from the entry point.

The goals are to:

* Encapsulate components and provide a managed entry point;
* Be explicit about dependencies—components in a component subdirectory may depend on each other, but outside components should only use the entry point
* Help us see what the relationships between components are and identify places where structure could be improved

In this variant, `index.js` is an entry point, aggregator module. In this case, I've re-exported `Annotation` as the default, but for other component collections (I'm foreseeing `Button` here), it's likely that there would be multiple named exports.

Mostly, this feels intuitively good. The only thing I don't like is how long paths are getting on import statements because we're nested...

### CODE REVIEW

**Comment by LMS007** [comment]
In terms of grouping related components into a subfolder, I agree we are probably are at that threshold and this is good first step. I like the index file to help abstract what public methods/components we want to export. The one area were I'm a bit concerned is with the sass to component mappings. Currently we duplicate the folder structure inside of src/styles and we would probably want to continue doing so with these component sub-folders (e.g. src/styles/components/Annotator/), otherwise why would there be a difference? Or is this the inflection point where we re-think how to organize the sass modules? I don't really have any good suggestions other than perhaps coupling them closer to the components themselves which may make sense?

For example

src/styles/ (same)
src/styles/mixins  (same)
src/sidebar/annotator/styles/  (new)
src/sidebar/annotator/component/styles/  (new)
src/sidebar/styles/  (new)
src/sidebar/components/styles/  (new)
src/sidebar/components/Annotation/styles/  (new)

This may be a bad idea for a lot of reasons not least of which means the .scss files are sprinkled in with the .js files, but it does help scope sass to components and couple them tighter to their respective components without duplicating folders. But perhaps for the sake of this PR we can just _not_ break the folder pattern and add /Annotation inside of /styles/components for the time being.

Thoughts?

**Comment by lyzadanger** [comment]
@LMS007 The lack of SCSS re-arrangement was a total oversight! Thank you for pointing it out. I'll take a look at it before advising how to proceed on this PR.

**Comment by robertknight** [comment]
I'm on board with the proposed pattern here as a way to group the subcomponents that make up some complex element into a package, of which only a subset are exported.

It would be nice if we could treat the `Annotation` folder as a namespace and avoid needing to repeat the `Annotation` prefix at the start of each component, but as long as our CSS classes live in a global namespace, keeping the full name is a practical way of keeping the two in sync. It's also handy for grep-ability.

Regarding styles, I can see two broad options:

- Colocate styles and source files more closely in the tree, somewhat like we do with tests and the code
- Mirror the component directory hierarchy. This second option would be a smaller change to the status quo, so perhaps worth doing as an intermediate step even if we decide to eventually colocate the styles

**Comment by lyzadanger** [comment]
> It would be nice if we could treat the Annotation folder as a namespace and avoid needing to repeat the Annotation prefix at the start of each component, but as long as our CSS classes live in a global namespace, keeping the full name is a practical way of keeping the two in sync. It's also handy for grep-ability.

Yeah, I started by doing that, but found that the uniqueness of module names was _very nice to have_. e.g. If we have a component, `AnnotationList` (not a real thing, but you get the idea) and this got truncated to `List.js` in the `Annotation` directory, it's a pain to find in one's editor/IDE/terminal/however you navigate your file/module structure. It also feels funky to have Pascal-cased module names that aren't the name of the component inside them. Though I started this little exercise highly in favor of removing the module-name redundancies as you are talking about here, I ended up on the other side of the fence once I got my hands dirty.

**Pull request merged**
