### PR TITLE
Use CrossFrame to show/hide the Sidebar

### PR DESCRIPTION
**Pull request by JCCR**
This is part of the ongoing development of multiple iframe document support.

Before these changes when a user clicks/taps on an area to hide the sidebar it could only be done at the top level frame. Because of the planned multi-frame support we need to introduce a change so other frames can do this hiding through `CrossFrame`.

Showing the sidebar is now relayed through `CrossFrame` as well. This is so the sub-frames can also bring up the sidebar when necessary.

The goal of this is to leave the original behaviour with a single top level frame intact, while setting up for the multi-frame support.

### CODE REVIEW

**Comment by sean-roberts** [comment]
This needs to be rebased @JCCR

**Comment by sean-roberts** [comment]
@JCCR Think you can rebase this today?

**Comment by JCCR** [comment]
Hi Sean,

I rebased recently and are going to fix the codecov issues that are now
being reported.

**Comment by JCCR** [comment]
@sean-roberts 
I see what happened. Rebasing again

**Comment by sean-roberts** [comment]
Thanks @JCCR Checking it out

**Pull request merged**
