### PR TITLE
Added links to help center from help panel

### PR DESCRIPTION
**Pull request by lenazun**
This modifies the link and text on the Help Panel to send users to the Help Center and help center form.

### CODE REVIEW

**Comment by robertknight** [comment]
Change LGTM. I edited the help page template slightly to wrap the message onto multiple lines to make it easier to read.

I have a query about the sign-in option on the help desk which I'd like to resolve if possible before we advertise the new help desk to users via the client. See https://hypothes-is.slack.com/archives/lounge/p1478262695002491

**Comment by lenazun** [comment]
Unfortunately we don't have the option to get rid of that Sign In option.  We get a very limited template from Zendesk.

**Comment by robertknight** [comment]
Could we change the description of the service from "Hypothes.is" to "Hypothesis Help Desk" for example, so that it is at least clear that users are not signing into the Hypothesis service?

**Comment by robertknight** [comment]
LGTM

**Pull request merged**
