### PR TITLE
Change button tag to span for the minimal onboarding look.

### PR DESCRIPTION
**Pull request by sheetaluk**
See hypothesis/product-backlog#351

### CODE REVIEW

**Comment by seanh** [comment]
Same comment, @sheetaluk can you please add some context to your commit message and the pull request description, explaining why this change is needed? Thanks

**Comment by sheetaluk** [comment]
@fatbusinessman and @seanh 
The new note button in the onboarding tutorial shouldn't be a button because it isn't clickable. It is there to teach the user what to look for to create a new note. I've turned that button element into a span with the same styling as the new note button which appears in the 'Page Notes' tab:
https://user-images.githubusercontent.com/2458/32885925-f228a64c-cab6-11e7-878c-9b593e667a97.png

This is coming from a comment in a related PR:
https://github.com/hypothesis/client/pull/580#discussion_r151372544

**Comment by seanh** [comment]
And I _think_ that to enable the eLife onboarding card you have to set [this config setting](https://github.com/hypothesis/client/pull/580) in the page that's being annotated (see [Configuring the Client](http://h.readthedocs.io/projects/client/en/latest/publishers/config/)). I don't think the publisher account test site has the new onboarding card?

**Comment by sheetaluk** [comment]
@seanh Yes. `enableCleanOnboardingTheme` is the config option for turning on the minimal look for the onboarding card. I have just pushed a PR for changes to the publisher account test site here: https://github.com/hypothesis/publisher-account-test-site/pull/25

**Comment by seanh** [comment]
@sheetaluk This also changes the shape / size (padding) of the button. Is that intentional?

**Comment by seanh** [comment]
@robertknight Since I'm going to be focused on the Disqus comments importer next week, I'm happy to hand this PR over to you for review and merge next week

**Comment by seanh** [comment]
@sheetaluk ping

**Comment by sheetaluk** [comment]
@seanh: @dawariley took a look at the changes and approved them, I'm happy to check with her again and go over the concerns mentioned and change anything else.

**Comment by seanh** [comment]
@sheetaluk I'm still not sure why we're changing the padding of the new note button in this pull request? Since the title of this PR is _Change button tag to span_. I don't mind these two small things being in the same pull request but I do think they need to be split into two separate commits. One is an HTML semantics code change, the other is a visual CSS tweak.

**Pull request merged**
