### PR TITLE
Edit assetRoot and sidebarAppUrl docs

### PR DESCRIPTION
**Pull request by seanh**
Move the docs for these two config settings into their own section in
the docs, and note that they're experimental.

### CODE REVIEW

**Comment by seanh** [comment]
@robertknight I believe these are the docs changes that you wanted from https://github.com/hypothesis/client/pull/270/files More to come

**Comment by seanh** [comment]
I've gone ahead and pushed an edit of the `services` docs to this branch as well

**Comment by robertknight** [comment]
LGTM. I modified the `assetRoot` docs to remove the reference to the `build/` suffix in the path because that part of the original PR was never merged.

**Comment by robertknight** [comment]
Rebased

**Pull request merged**
