### PR TITLE
Convert annotator component modules to PascalCase

### PR DESCRIPTION
**Pull request by lyzadanger**
Just some housekeeping...

Fixes https://github.com/hypothesis/client/issues/2987

### CODE REVIEW

**Review by LMS007 — APPROVED** [review]
Can you remind me again the TODOs for css class names with pascal casing and/or matching the the classname to the component's class name?

**Comment by LMS007** [comment]
> Can you remind me again the TODOs for css class names with pascal casing and/or matching the the classname to the component's class name?

in other words, is the plan to eventually have the classname match the component name exactly?

**Comment by lyzadanger** [comment]
> Can you remind me again the TODOs for css class names with pascal casing and/or matching the the classname to the component's class name? in other words, is the plan to eventually have the classname match the component name exactly?

Yeah, the TODO is I TOTALLY FORGOT TO DO THIS—it should have been handled here. I'll fix.

**Comment by lyzadanger** [comment]
@LMS007 The situation is more nuanced than I thought. I have Pascal-cased the SASS module names for the existing annotator-component SASS modules, but I have left the class-naming inside them alone for now. There's a bit more work to be done here to really "component-ize" the annotator UI. There isn't a clear mapping from SASS component/block to annotator component, yet.

Anyway, let me know if this is good to land.

**Comment by LMS007** [comment]
> @LMS007 The situation is more nuanced than I thought. I have Pascal-cased the SASS module names for the existing annotator-component SASS modules, but I have left the class-naming inside them alone for now. There's a bit more work to be done here to really "component-ize" the annotator UI. There isn't a clear mapping from SASS component/block to annotator component, yet.
> 
> Anyway, let me know if this is good to land.

Yes, I took a look too and it didn't seem obvious how to change some of those around. The annotator is a bit different than the sidebar in its standards of css class names.

**Comment by lyzadanger** [comment]
@LMS007 Ping. Is this good to go?

**Review by LMS007 — APPROVED** [review]

**Pull request merged**
